"""fix column name error

Revision ID: 15c67e70d3bd
Revises: a4392b030418
Create Date: 2017-09-08 13:55:30.309135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c67e70d3bd'
down_revision = 'a4392b030418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'comfirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
