"""add JSON Web Signatures

Revision ID: a4392b030418
Revises: fc1d50b1ee0a
Create Date: 2017-09-08 13:15:31.258719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4392b030418'
down_revision = 'fc1d50b1ee0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comfirmed')
    # ### end Alembic commands ###
